services:
  db:
    container_name: attendance_db
    # runs the image everytime the container starts EXCEPT if stopped. run with "docker compose up" after if needed
    restart: unless-stopped
    image: mariadb:10.6
    # initial settings of the database
    # change the values to your specifications (especially the timezone/TZ)
    env_file:
      - path: ./.env
        required: true
    # enable port 3306 on host to access db from database managers like DBeaver and MySQL Workbench
    ports:
      - 3306:3306
    volumes:
      - ./backend/config/initial_db:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    # disable database Strict Mode
    command: mysqld --sql_mode=""
    networks:
      - attendance_network
  backend:
    container_name: attendance_backend
    # runs the image everytime the container starts EXCEPT if stopped. run with "docker compose up" after if needed
    restart: unless-stopped
    depends_on:
      - db
    image: attendance-backend
    env_file:
      - path: ./.env
        required: true
    volumes:
      - "./backend/:/var/www/html"
      - "./backend/config/php.ini:/usr/local/etc/php/php.ini"
    ports:
      - 2024:80
    networks:
      - attendance_network
networks:
  attendance_network:
    driver: bridge
volumes:
  mysql_data: